# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='plugins/')),
            ],
        ),
    ]
