# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadasta_plugins', '0003_release'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['name']},
        ),
    ]
