# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadasta_plugins', '0004_auto_20170503_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='qgis_maximum_version',
            field=models.CharField(default='2.14', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='qgis_minimum_version',
            field=models.CharField(default='2.18', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(default='plugin_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
